### ISSUE TITLE
Orchestrator: Service Logic for Timeout

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#588]
When a task reaches its timeout limit it should set into an error state with the errorcode 'Timeout'

**Comment by martinfkaeser** [comment]
In the refinement session we further discussed the details.

Two different kinds of timeout should be checked:
- A task remaining in state "Pending" for a specified time should go into state "Error" with error type "Timeout": *TaskPendingTimeout*
- A specified time after reaching its final state ("Success" or "Error") the task should be completely removed from the Orchestrator: *TaskRetentationTime*

**Comment by martinfkaeser** [comment]
During implementation this problem came up:
In our current API we return just *one timeout* when reserving *several tasks* for cleaning.
But each task can have a different timeout, because it is calculated as **task.creationTime** + **taskPendingTimeout**.

So I would suggestion moving the timeout down to the task data.
Now I realized in ReDoc the API has already been changed exactly like that:
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/eclipse-tractusx/bpdm/docs/api/generic-input/docs/api/orchestrator-proposal.yaml#tag/Cleaning-Steps/paths/~1cleaning-tasks~1reservation/post
So I'll update the implementation.

**Comment by nicoprow** [comment]
Ok, seems to be we did not ahere to the OpenAPI spec completely in that regard. Nevertheless we should e careful about introducing breaking changes into the BPDM applications. If the feature will need to be a breaking change the time when we can merge it may increase. A minor version update could be simpler: Just leave the global timeout and add the timeout field for each indiviudal task. 

We should plan ahead when we want to introduce the next breaking change to see how much we need to consider this aspect for the feature

**Comment by martinfkaeser** [comment]
Okay, I'll mark the global *timeout* field as deprecated.

I'm wondering if in the reservation result a timeout even makes sense or if we should remove it completely?
After all it is not only the timeout for posting the result but for completely processing the task.
If a cleaning service posts the cleaning results e.g. 10 secs before the announced timeout this will probably not be enough because the Pool still needs to process the task in the remaining time. 
The problem would be exacerbated if there are multiple cleaning steps.

What do you think, @nicoprow ?
