### ISSUE TITLE
security context root for modifing opensearch filesystem dependency

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/bpdm#659]
Hi BPDM-Team,

found an opensearch dependency in our helm chart that is a against our rule with https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03

After a little Chat and research with our System Team Member this should be clarified till the next release. 

Problem: `runAsUser: 0`

https://github.com/eclipse-tractusx/bpdm/blob/700af9a6edd6479bb2539a2ed3b9d586a1f417f4/charts/bpdm/values.yaml#L53-L73

And guess there are also some opensearch values you can play arround with
https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml

But also other users seems to have the problem:
https://github.com/opensearch-project/helm-charts/issues/369
https://github.com/opensearch-project/helm-charts/issues/480

Bitnami approach:
https://github.com/bitnami/charts/blob/2ba572d7ec51d5ff9ecd47f5748aab308aef693e/bitnami/elasticsearch/templates/data-statefulset.yaml#L72

Clear announcement that we have to discuss this and you as a bpdm-team have to push the topic.

**Comment by FaGru3n** [comment]
@Siegfriedk FYI

**Comment by Siegfriedk** [comment]
I unassigned myself as i expect a collegue/team member of bpdm to drive this.

General speaking: if this is a dependency were you do not expect someome else to use an external setup or managed, it become a component of your product and need to be able to run as non root.

It should also not be hard to fix it

**Comment by Siegfriedk** [comment]
@nicoprow out of curiosity: what did you use it for and how are you replacing it?

**Comment by nicoprow** [comment]
> @nicoprow out of curiosity: what did you use it for and how are you replacing it?

In the past we had a functionality to search business partners by different text fields such as names, descriptions such like that. At that time it seemed that the requirements would lead to more complex search functionality over the business partners. However, we never actually experienced that demand and with a drastic data model change the existing search functionality was also scaled back. 
Because of this, we decided that a normal database fuzzy search will currently suffice for the business partner search. We have already intorduced a fairly simple database search as an alternative to Opensearch and therefore, we are able to remove the whole Opensearch component soon.
